all: Node.class Operator.class Natural.class PrintableTree.class

Node.class: Node.java
	javac -cp ../.. Node.java

Operator.class: Operator.java
	javac -cp ../../ Operator.java

Natural.class: Natural.java
	javac -cp ../../ Natural.java

PrintableTree.class: PrintableTree.java
	javac -cp ../../ PrintableTree.java
