all: Controller.class ControllerInterface.class

Controller.class: Controller.java
	javac -cp ../../ Controller.java

ControllerInterface.class: ControllerInterface.java
	javac -cp ../../ ControllerInterface.java
