all: Page.class ViewNode.class NodeTextField.class NodeLabel.class EditableSet.class EditMode.class

Page.class: Page.java
	javac -cp ../.. Page.java

ViewNode.class: ViewNode.java
	javac -cp ../../ ViewNode.java

NodeTextField.class: NodeTextField.java
	javac -cp ../../ NodeTextField.java

NodeLabel.class: NodeLabel.java
	javac -cp ../../ NodeLabel.java

EditableSet.class: EditableSet.java
	javac -cp ../../ EditableSet.java

EditMode.class: EditMode.java
	javac -cp ../../ EditMode.java
